services:
  php:
    build: ./backend
    container_name: php_app
    working_dir: /app
    environment:
      APP_DB_HOST: db
      APP_DB_PORT: ${POSTGRES_PORT}
      APP_DB_NAME: ${POSTGRES_DB}
      APP_DB_USER: ${POSTGRES_USER}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backend/public:/app/public
      - ./backend/src:/app/src
      - ./backend/bootstrap:/app/bootstrap
      - ./backend/db:/app/db
      - ./backend/phinx.php:/app/phinx.php
      - ./backend/composer.json:/app/composer.json
      - ./backend/composer.lock:/app/composer.lock
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        vendor/bin/phinx migrate &&
        vendor/bin/phinx seed:run &&
        php -S 0.0.0.0:8000 -t public
      "
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - php

volumes:
  postgres_data: